
   DECLARE            @ID_GESTION   INT,                            
                                @FECHA        DATE ,
		@ID_CEDENTE   INT

   SET @FECHA = GETDATE()
   SET @ID_CEDENTE = 9			 -- 9 = AVN                                             
	
  DECLARE RECORRE_GESTIONES CURSOR FOR
   
   SELECT            A.ID_GESTION       
   FROM               IBR_ALO..[GESTION] A
   INNER JOIN     IBR_ALO..[CLIENTE] B
   ON                    A.ID_CLIENTE = B.ID_CLIENTE
   WHERE            B.ID_CEDENTE = @ID_CEDENTE 
   AND                  A.FECHA_GESTION  >= @FECHA 
   AND                  A.FECHA_GESTION  < DATEADD(DD,1,@FECHA) 
   AND                  A.ID_GESTION NOT IN (SELECT ID_GESTION_ALO FROM TECNOCOB..TMP_MIGRACION_ALO_CREATE_GESTION)   

   OPEN RECORRE_GESTIONES
   FETCH NEXT FROM RECORRE_GESTIONES
   INTO                  @ID_GESTION                       

   WHILE @@FETCH_STATUS = 0  
      BEGIN


--EJECUTTA PROCEDIMIENTO PARA MIGRAR GESTIONES DE IBR_ALO A TECNOCOB
EXEC  TECNOCOB.DBO.SP_MIGRACION_ALO_CREATE_GESTION
	                                   @ID_GESTION 


-- INSERTA REGISTRO DEL ID DE GESTION MIGRADO EN UNA TABLA DE HISTORICO
INSERT INTO TECNOCOB..TMP_MIGRACION_ALO_CREATE_GESTION
           ([ID_GESTION_ALO]
           ,[FECHA])
     VALUES
           (@ID_GESTION
           ,GETDATE())
     

         FETCH NEXT FROM RECORRE_GESTIONES
         INTO                  @ID_GESTION 

      END
CLOSE RECORRE_GESTIONES
DEALLOCATE RECORRE_GESTIONES





/*
INSERT INTO tecnocob.DBO.TBL_TELEFONIA_GESTIONES(fld_rut_cli	,fld_cod_emp	,fld_tip_ges	
,fld_cod_ges	,fld_cod_res	,fld_res_cli	,fld_tip_con	,fld_can_ges	,fld_cod_usu	
,fld_fec_ges	,fld_num_tel	,fld_comenta	,fld_cod_acc	,fld_nom_cam	,fld_fecha_visita)
SELECT CAST(CLI.IDENTIFICADOR AS VARCHAR(11)) AS fld_rut_cli
      ,CAST(CED.DESCRIPCION AS VARCHAR(3))    AS fld_cod_emp
	  ,TGE.ID_TIPO_GESTION AS fld_tip_ges
	  ,1 AS fld_cod_ges
	  ,HGE.FLD_COD_RES AS fld_cod_res
	  ,HGE.FLD_RES_CLI AS fld_res_cli
	  ,TPC.ID_TIPO_CONTACTO AS fld_tip_con
	  ,1 AS fld_can_ges
	  ,CAST(USU.LOGIN AS VARCHAR(8)) AS fld_cod_usu
	  ,GES.FECHA_GESTION AS fld_fec_ges
	  ,CASE
	      WHEN MCO.DESCRIPCION IN ('TELEFONO', 'SMS', 'IVR') 
		     THEN CAST(TEL.FONO_DISCAR AS VARCHAR(15))
	   END AS fld_num_tel
	  ,CAST(GES.COMENTARIO AS VARCHAR(250)) AS fld_comenta
	  ,'' AS fld_cod_acc
	  ,GES.INTERACCION_DISCADOR AS fld_nom_cam
	  ,'19000101' as fld_fecha_visita
      --,*       
  FROM GESTION GES
 INNER JOIN 
       CLIENTE CLI
	ON GES.ID_CLIENTE = CLI.ID_CLIENTE
 INNER JOIN 
       USUARIO USU
	ON GES.ID_USUARIO = USU.ID_USUARIO
 INNER JOIN 
       CEDENTE CED
    ON CLI.ID_CEDENTE = CED.ID_CEDENTE
 INNER JOIN 
       SUB_RESPUESTA SRE
	ON GES.ID_SUB_RESPUESTA = SRE.ID_SUB_RESPUESTA
 INNER JOIN
       RESPUESTA RES
	ON RES.ID_RESPUESTA = SRE.ID_RESPUESTA
 INNER JOIN 
       TIPO_GESTION TGE
    ON RES.ID_TIPO_GESTION = TGE.ID_TIPO_GESTION
 INNER JOIN 
       MEDIO_CONTACTO MCO
	ON MCO.ID_MEDIO_CONTACTO = RES.ID_MEDIO_CONTACTO
 INNER JOIN
       TELEFONO TEL
	ON GES.NRO_DEPENDIENTE = TEL.ID_TELEFONO
 INNER JOIN
       TIPO_CONTACTO TPC
	ON TPC.ID_TIPO_CONTACTO = RES.ID_TIPO_CONTACTO
 INNER JOIN HOMOLAGACION_GESTION HGE
    ON HGE.ID_RESPUESTA = RES.ID_RESPUESTA
   AND HGE.ID_SUB_RESPUESTA = SRE.ID_SUB_RESPUESTA
 WHERE USU.LOGIN not IN ('admin','jesus.umana','cperez','pagiuval', 'soporteibr')
   AND GES.FECHA_GESTION >= '' +CONVERT(VARCHAR,GETDATE(),112)+ ' 00:00:00'
   AND GES.FECHA_GESTION <= '' +CONVERT(VARCHAR,GETDATE(),112)+ ' 23:59:59'
 ORDER BY GES.FECHA_GESTION ASC
*/


/*
INSERT INTO tecnocob.dbo.tbl_telefonia_comp_pago (
 fld_cod_emp, fld_rut_cli, fld_fec_ing, fld_fec_com, fld_mon_com, fld_for_pag, fld_tip_com, fld_lug_pag, fld_num_tel, 
 fld_cod_usu, fld_est_com, fld_observacion, fld_num_ref, fld_cant_cuo, fld_id_gestion)

SELECT CAST(CED.DESCRIPCION AS VARCHAR(3))  AS FLD_COD_EMP
      ,CLI.IDENTIFICADOR                    AS FLD_RUT_CLI
	  ,GES.FECHA_GESTION                    AS FLD_FEC_ING
	  ,COM.FECHA_COMPROMISO                 AS FLD_FEC_COM
	  ,CAST(COM.MONTO_COMPROMISO AS MONEY)  AS FLD_MON_COM
	  ,1                                    AS FLD_FOR_PAG
	  ,COM.ID_TIPO_COMPROMISO               AS FLD_TIP_COM
	  ,14                                   AS FLD_LUG_PAG
	  ,CASE
	      WHEN MCO.DESCRIPCION IN ('TELEFONO', 'SMS', 'IVR') 
		     THEN CAST(TEL.FONO_DISCAR AS VARCHAR(15))
	   END                                  AS FLD_NUM_TEL
	  ,LOWER(USU.LOGIN)                     AS FLD_COD_USU
	  ,CASE
	      WHEN ECO.ID_ESTADO_COMPROMISO_PAGO = 1 THEN 1
		  WHEN ECO.ID_ESTADO_COMPROMISO_PAGO = 2 THEN 2
		  WHEN ECO.ID_ESTADO_COMPROMISO_PAGO = 3 THEN 5
	   END                                  AS FLD_EST_COM
	  ,CAST(GES.COMENTARIO AS VARCHAR(60)) AS FLD_OBSERVACION
	  ,'N/A'                                AS FLD_NUM_REF
	  ,0                                    AS FLD_CANT_CUO
	  ,0                                    AS FLD_ID_GESTION
  FROM IBR_ALO..GESTION GES
 INNER JOIN
       IBR_ALO..CLIENTE CLI
 	 ON GES.ID_CLIENTE = CLI.ID_CLIENTE
 INNER JOIN 
       IBR_ALO..USUARIO USU
	ON GES.ID_USUARIO = USU.ID_USUARIO
 INNER JOIN 
       IBR_ALO..CEDENTE CED
    ON CLI.ID_CEDENTE = CED.ID_CEDENTE
 INNER JOIN
       IBR_ALO..COMPROMISO_PAGO COM
	ON GES.ID_GESTION = COM.ID_GESTION
 INNER JOIN 
       IBR_ALO..ESTADO_COMPROMISO_PAGO ECO
	ON ECO.ID_ESTADO_COMPROMISO_PAGO = COM.ID_ESTADO_COMPROMISO_PAGO
 INNER JOIN 
       IBR_ALO..SUB_RESPUESTA SRE
	ON GES.ID_SUB_RESPUESTA = SRE.ID_SUB_RESPUESTA
 INNER JOIN
       IBR_ALO..RESPUESTA RES
	ON RES.ID_RESPUESTA = SRE.ID_RESPUESTA
 INNER JOIN 
       IBR_ALO..TIPO_GESTION TGE
    ON RES.ID_TIPO_GESTION = TGE.ID_TIPO_GESTION
 INNER JOIN 
       IBR_ALO..MEDIO_CONTACTO MCO
	ON MCO.ID_MEDIO_CONTACTO = RES.ID_MEDIO_CONTACTO
 INNER JOIN
       IBR_ALO..TELEFONO TEL
	ON GES.NRO_DEPENDIENTE = TEL.ID_TELEFONO
 INNER JOIN
       IBR_ALO..TIPO_CONTACTO TPC
	ON TPC.ID_TIPO_CONTACTO = RES.ID_TIPO_CONTACTO
 INNER JOIN 
       IBR_ALO..HOMOLAGACION_GESTION HGE
    ON HGE.ID_RESPUESTA = RES.ID_RESPUESTA
   AND HGE.ID_SUB_RESPUESTA = SRE.ID_SUB_RESPUESTA
 INNER JOIN 
       IBR_ALO..TIPO_ACCION TAC
	ON TAC.ID_TIPO_ACCION = GES.ID_TIPO_ACCION
   AND TAC.ID_SUB_RESPUESTA = SRE.ID_SUB_RESPUESTA
 WHERE CED.DESCRIPCION = 'CVI'
   AND GES.FECHA_GESTION >= '' +CONVERT(VARCHAR,GETDATE(),112)+ ' 00:00:00'
   AND GES.FECHA_GESTION <= '' +CONVERT(VARCHAR,GETDATE(),112)+ ' 23:59:59'

*/
